SUPABASE_URL = "https://alnbvzktqgjqnoxgusij.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsbmJ2emt0cWdqcW5veGd1c2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDgyNTgsImV4cCI6MjA2OTY4NDI1OH0.p6XQX0MTXA8Yh1NqSj92VLa06H3czJhDL7psWOziRGs"
[auth]
admin_password = "NerY102201"

